"""phase1_foundation_schema

Revision ID: ba85a320df0c
Revises: 
Create Date: 2026-05-24 14:28:45.431499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = 'ba85a320df0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension — must exist before voice_samples table is created.
    # Safe to run on Neon where extension was already enabled; IF NOT EXISTS is idempotent.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ghl_company_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('white_label_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ghl_company_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('ghl_location_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ghl_location_id')
    )
    op.create_index('idx_locations_account', 'locations', ['account_id'], unique=False)
    op.create_table('blueprints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('market_city', sa.Text(), nullable=True),
    sa.Column('brokerage', sa.Text(), nullable=True),
    sa.Column('years_active', sa.Text(), nullable=True),
    sa.Column('price_range', sa.Text(), nullable=True),
    sa.Column('niche_primary', sa.Text(), nullable=True),
    sa.Column('niche_secondary', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('voice_tone', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('voice_cadence', sa.Text(), nullable=True),
    sa.Column('vocabulary_yes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('vocabulary_no', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('pov', sa.Text(), server_default='first-person', nullable=True),
    sa.Column('humor_level', sa.Text(), nullable=True),
    sa.Column('audience_primary', sa.Text(), nullable=True),
    sa.Column('audience_pain_points', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('audience_aspirations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('one_liner', sa.Text(), nullable=True),
    sa.Column('differentiators', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('proof_points', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('pillars', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('vyral_mix', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"viral": 0.4, "brand": 0.3, "personal": 0.2, "conversion": 0.1}\''), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('foundation_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_foundation_scores_location', 'foundation_scores', ['location_id', 'computed_at'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('provider_account_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'provider', name='uq_oauth_tokens_location_provider')
    )
    op.create_table('user_location_access',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'location_id')
    )
    op.create_table('voice_samples',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('bucket', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('edit_distance', sa.Float(), nullable=True),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('excluded', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('promoted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voice_samples_embedding', 'voice_samples', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    op.create_index('idx_voice_samples_filter', 'voice_samples', ['location_id', 'platform', 'bucket', 'excluded'], unique=False)
    op.create_index('idx_voice_samples_location', 'voice_samples', ['location_id'], unique=False)
    op.drop_table('playing_with_neon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_index('idx_voice_samples_location', table_name='voice_samples')
    op.drop_index('idx_voice_samples_filter', table_name='voice_samples')
    op.drop_index('idx_voice_samples_embedding', table_name='voice_samples', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    op.drop_table('voice_samples')
    op.drop_table('user_location_access')
    op.drop_table('oauth_tokens')
    op.drop_index('idx_foundation_scores_location', table_name='foundation_scores')
    op.drop_table('foundation_scores')
    op.drop_table('blueprints')
    op.drop_index('idx_locations_account', table_name='locations')
    op.drop_table('locations')
    op.drop_table('users')
    op.drop_table('accounts')
    # ### end Alembic commands ###
