"""phase2a_posts_variants_attempts

Revision ID: d03de2d7e071
Revises: ba85a320df0c
Create Date: 2026-05-26 21:45:48.339752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd03de2d7e071'
down_revision: Union[str, None] = 'ba85a320df0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('bucket', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("bucket IN ('viral', 'brand', 'personal', 'conversion', 'podcast') OR bucket IS NULL", name='ck_posts_bucket'),
    sa.CheckConstraint("source IN ('post_forge', 'auto_plan', 'manual', 'clip_distributor', 'brick_proposed') OR source IS NULL", name='ck_posts_source'),
    sa.CheckConstraint("status IN ('draft', 'scheduled', 'publishing', 'published', 'partially_published', 'failed')", name='ck_posts_status'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_location_status', 'posts', ['location_id', 'status', 'created_at'], unique=False)
    op.create_table('post_variants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('first_comment', sa.Text(), nullable=True),
    sa.Column('media_urls', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('platform_specific', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.CheckConstraint("platform IN ('linkedin', 'instagram', 'facebook', 'tiktok', 'youtube', 'x', 'gmb', 'threads')", name='ck_post_variants_platform'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'platform', name='uq_post_variants_post_platform')
    )
    op.create_table('post_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), server_default='ghl', nullable=False),
    sa.Column('provider_post_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'sent_to_provider', 'published', 'failed')", name='ck_post_attempts_status'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['post_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_post_attempts_post', 'post_attempts', ['post_id'], unique=False)
    op.create_index('idx_post_attempts_variant', 'post_attempts', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_post_attempts_variant', table_name='post_attempts')
    op.drop_index('idx_post_attempts_post', table_name='post_attempts')
    op.drop_table('post_attempts')
    op.drop_table('post_variants')
    op.drop_index('idx_posts_location_status', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
