"""
services/media/muse.py — Meta Muse adapter: text (`complete`) and image (`generate_image`).

VERIFIED FACTS (supplied by the spec owner, see docs/MEDIA_PROVIDERS_VERIFIED.md):

- Base ``https://api.meta.ai/v1``, header ``Authorization: Bearer <key>``; the key
  comes from dev.meta.ai (setting ``meta_model_api_key``, env ``MODEL_API_KEY``).
- OpenAI-compatible ``POST /v1/chat/completions``. Default model ``muse-spark-1.3``.
- ``-contributor`` variants are cheaper but Meta MAY USE prompts/outputs for
  training. Standard is the default; contributor is opt-in via
  ``META_MUSE_ALLOW_CONTRIBUTOR=1`` and is REFUSED whenever the caller marks the
  input as containing client/lead PII (``pii=True``).
- Image model ``muse-image`` ($0.01/image, 150 rpm). US-only public preview.
  Reasoning tokens are billed as output, so ``max_tokens`` is always capped.

NOT VERIFIED: the image route. We assume the OpenAI-compatible
``POST /v1/images/generations`` with ``{model, prompt, n:1}`` and a response of
``data[0].b64_json`` or ``data[0].url``. If Meta's route differs the image path
fails loudly (ProviderError), it never guesses.

Acceptable-use rules this adapter enforces or supports:
- Outputs must not be presented as human-written: every result carries
  ``ai_generated=True`` and callers keep the disclosure.
- Provenance (watermark / C2PA / any metadata fields Meta attaches to
  muse-image outputs) is preserved verbatim: image bytes are written untouched,
  every non-pixel field and provenance-looking response header is returned in
  ``MuseImage.provenance`` and saved next to the file.
- No fake reviews/engagement and no impersonating a real person's voice or
  face: callers' responsibility; runners must not route such requests here.

Cost discipline: missing key => ProviderNotConfigured before any network call;
prompt-size and max_tokens caps are enforced before the call; a timeout after
the POST is uncertain (tokens may be billed) => ProviderUncertainError, never
retried; 5xx is not retried; 429 backs off then gives up.
"""

import base64
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import httpx

from services.media import base
from services.media.base import (
    GenerationRequest,
    MediaAsset,
    MediaProvider,
    MediaProviderError,
    ProviderAuthError,
    ProviderCapExceeded,
    ProviderError,
    ProviderNotConfigured,
    ProviderQuotaError,
    ProviderRateLimited,
    ProviderUncertainError,
)

BASE_URL = "https://api.meta.ai/v1"
DEFAULT_MODEL = "muse-spark-1.3"
KNOWN_TEXT_MODELS = ("muse-spark-1.3", "muse-spark-1.2", "muse-spark-1.1")
CONTRIBUTOR_SUFFIX = "-contributor"
DEFAULT_IMAGE_MODEL = "muse-image-1.0"
DEFAULT_MAX_TOKENS = 2048
DEFAULT_MAX_TOKENS_CAP = 8192
DEFAULT_MAX_PROMPT_CHARS = 100000
DEFAULT_TIMEOUT_S = 120
RATE_LIMIT_BACKOFF = (5.0, 15.0, 45.0)
ENV_KEY = "MODEL_API_KEY"
AI_DISCLOSURE = "Generated by AI (Meta Muse). Do not present as human-written."

_MODEL_RE = re.compile(r"^muse-[a-z0-9][a-z0-9.\-]{0,63}$")
_REGION_WORDS = ("region", "country", "location", "geograph", "united states", "u.s.", "not available in your", "unsupported territory")
_QUOTA_WORDS = ("quota", "credit", "billing", "insufficient")
_PROVENANCE_HEADER_WORDS = ("provenance", "c2pa", "watermark", "synthid", "content-credential", "meta-ai")


@dataclass
class MuseCompletion:
    text: str
    model: str
    usage: Dict[str, Any] = field(default_factory=dict)   # prompt/completion (incl. reasoning) tokens
    ai_generated: bool = True
    disclosure: str = AI_DISCLOSURE


@dataclass
class MuseImage:
    data: bytes                       # exactly what Meta sent — never re-encoded or stripped
    mime: str
    model: str
    provenance: Dict[str, Any] = field(default_factory=dict)
    ai_generated: bool = True
    disclosure: str = AI_DISCLOSURE


def _truthy(value: Any) -> bool:
    return str(value or "").strip().lower() in ("1", "true", "yes", "on")


def _body_text(resp: httpx.Response) -> str:
    try:
        return resp.text[:2000].lower()
    except Exception:
        return ""


class MuseProvider(MediaProvider):
    name = "muse"
    capabilities = frozenset({"text_to_image"})   # text goes through complete(); no text capability exists in base.CAPABILITIES

    # ── config ──
    def _key(self) -> str:
        return str(base.setting("meta_model_api_key", "") or base.setting("model_api_key", "") or "")

    def is_configured(self) -> bool:
        return bool(self._key())

    @property
    def contributor_allowed(self) -> bool:
        return _truthy(base.setting("meta_muse_allow_contributor", ""))

    @property
    def default_model(self) -> str:
        return str(base.setting("meta_muse_model", DEFAULT_MODEL) or DEFAULT_MODEL)

    @property
    def image_model(self) -> str:
        return str(base.setting("meta_muse_image_model", DEFAULT_IMAGE_MODEL) or DEFAULT_IMAGE_MODEL)

    @property
    def timeout_s(self) -> float:
        return float(max(1, base.setting_int("meta_muse_timeout_s", DEFAULT_TIMEOUT_S)))

    def _headers(self) -> Dict[str, str]:
        return {"Authorization": f"Bearer {self._key()}"}

    def _require_key(self) -> None:
        if not self.is_configured():
            raise ProviderNotConfigured(
                "Muse key missing", provider=self.name,
                user_message=f"Muse isn't connected — add {ENV_KEY} (key from dev.meta.ai) to .env and restart the server.",
            )

    # ── guards (all run before any network call) ──
    def resolve_model(self, model: Optional[str], contributor: bool, pii: bool) -> str:
        """Pick the model id. Standard unless contributor is explicitly opted into.

        - pii=True never reaches a -contributor model: an explicit request is
          refused; a global opt-in setting silently downgrades to standard.
        - An explicit contributor request without the opt-in setting is refused.
        """
        requested = (model or "").strip()
        if requested and not _MODEL_RE.match(requested):
            raise ProviderCapExceeded(
                "bad model id", provider=self.name,
                user_message="That isn't a Muse model name — use a muse-spark-* model.",
            )
        explicit_contrib = bool(contributor) or requested.endswith(CONTRIBUTOR_SUFFIX)
        if explicit_contrib and pii:
            raise MediaProviderError(
                "contributor refused for PII", provider=self.name,
                user_message=("Not sending this one through the contributor tier — it holds client or lead details, "
                              "and Meta may train on contributor prompts. Use the standard Muse model."),
            )
        if explicit_contrib and not self.contributor_allowed:
            raise MediaProviderError(
                "contributor not enabled", provider=self.name,
                user_message="The contributor tier is switched off — Meta may train on those prompts. Set META_MUSE_ALLOW_CONTRIBUTOR=1 to allow it.",
            )
        chosen = requested or self.default_model
        if chosen.endswith(CONTRIBUTOR_SUFFIX) and pii:
            chosen = chosen[: -len(CONTRIBUTOR_SUFFIX)]
        if contributor and not chosen.endswith(CONTRIBUTOR_SUFFIX):
            chosen += CONTRIBUTOR_SUFFIX
        return chosen

    def resolve_max_tokens(self, requested: Optional[int]) -> int:
        cap = max(1, base.setting_int("meta_muse_max_tokens_cap", DEFAULT_MAX_TOKENS_CAP))
        want = requested if requested is not None else base.setting_int("meta_muse_max_tokens", DEFAULT_MAX_TOKENS)
        try:
            want = int(want)
        except (TypeError, ValueError):
            want = DEFAULT_MAX_TOKENS
        return max(1, min(want, cap))

    def check_prompt(self, *parts: Optional[str]) -> None:
        limit = base.setting_int("meta_muse_max_prompt_chars", DEFAULT_MAX_PROMPT_CHARS)
        total = sum(len(p or "") for p in parts)
        if total > limit:
            raise ProviderCapExceeded(
                f"{total} chars > cap {limit}", provider=self.name,
                user_message=f"That prompt is {total:,} characters — the cap is {limit:,}. Trim it or raise META_MUSE_MAX_PROMPT_CHARS.",
            )

    # ── errors ──
    def _auth_or_region(self, status: int, body: str) -> MediaProviderError:
        if any(w in body for w in _REGION_WORDS):
            return ProviderError(
                f"region {status}", provider=self.name,
                user_message="Muse is only open in the US right now — this job site is outside the permit area.",
            )
        return ProviderAuthError(
            f"auth {status}", provider=self.name,
            user_message=f"Muse turned the key down — check {ENV_KEY} (from dev.meta.ai) and restart.",
        )

    def _quota(self) -> ProviderQuotaError:
        return ProviderQuotaError("quota", provider=self.name,
                                  user_message="Muse needs billing sorted — add a payment method or top up at dev.meta.ai, then run it again.")

    async def _post(self, path: str, payload: Dict[str, Any]) -> httpx.Response:
        """One write. Retries only definite 429s; returns the 200 response."""
        rate_tries = 0
        async with base.http_client(timeout=self.timeout_s) as client:
            while True:
                try:
                    resp = await client.post(f"{BASE_URL}{path}", headers=self._headers(), json=payload)
                except httpx.ConnectError as exc:
                    raise ProviderError(
                        f"connect failed: {type(exc).__name__}", provider=self.name,
                        user_message="Couldn't reach Muse — check the connection and run it again.",
                    )
                except httpx.TransportError as exc:  # timeout / reset after send: uncertain
                    raise ProviderUncertainError(
                        f"no response: {type(exc).__name__}", provider=self.name,
                        user_message="Didn't hear back from Muse — check your dev.meta.ai usage before running again.",
                    )
                status = resp.status_code
                if status == 200:
                    return resp
                body = _body_text(resp)
                if status in (401, 403):
                    raise self._auth_or_region(status, body)
                if status == 402 or (status in (400, 429) and any(w in body for w in _QUOTA_WORDS)):
                    raise self._quota()
                if status == 429:
                    if rate_tries >= len(RATE_LIMIT_BACKOFF):
                        raise ProviderRateLimited(
                            "rate limited", provider=self.name,
                            user_message="Muse is busy — give it a minute and run it again.",
                        )
                    await base.sleep(RATE_LIMIT_BACKOFF[rate_tries])
                    rate_tries += 1
                    continue
                raise ProviderError(
                    f"http {status}", provider=self.name,
                    user_message=f"Muse refused the request (HTTP {status}).",
                )

    # ── text ──
    async def complete_detailed(self, prompt: str, system: Optional[str] = None, pii: bool = False,
                                model: Optional[str] = None, contributor: bool = False,
                                max_tokens: Optional[int] = None, temperature: Optional[float] = None) -> MuseCompletion:
        self._require_key()
        if not (prompt or "").strip():
            raise ValueError("Nothing to ask — the prompt is empty.")
        self.check_prompt(prompt, system)
        chosen = self.resolve_model(model, contributor, pii)
        messages: List[Dict[str, str]] = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})
        payload: Dict[str, Any] = {"model": chosen, "messages": messages,
                                   "max_tokens": self.resolve_max_tokens(max_tokens), "stream": False}
        if temperature is not None:
            payload["temperature"] = temperature
        resp = await self._post("/chat/completions", payload)
        try:
            data = resp.json()
            content = data["choices"][0]["message"]["content"]
        except Exception:
            raise ProviderError("unexpected response shape", provider=self.name,
                                user_message="Muse sent back something we couldn't read.")
        if isinstance(content, list):
            content = "".join(str(p.get("text", "")) for p in content if isinstance(p, dict))
        text = str(content or "").strip()
        if not text:
            try:
                finish = data["choices"][0].get("finish_reason")
            except Exception:
                finish = None
            if finish == "length":
                # Reasoning tokens bill as output and share max_tokens: a tight cap can be spent
                # entirely on thinking, leaving no visible answer. Re-running won't fix that.
                raise ProviderError("max_tokens spent on reasoning", provider=self.name,
                                    user_message="Muse used up its page limit thinking before it wrote anything — raise the token cap and run it again.")
            raise ProviderError("empty completion", provider=self.name,
                                user_message="Muse sent back an empty page — run it again.")
        usage = data.get("usage") if isinstance(data.get("usage"), dict) else {}
        return MuseCompletion(text=text, model=chosen, usage=usage)

    async def complete(self, prompt: str, system: Optional[str] = None, pii: bool = False, **kwargs: Any) -> str:
        """Runner entry point: the completion text. Pass pii=True for any client/lead data."""
        return (await self.complete_detailed(prompt, system=system, pii=pii, **kwargs)).text

    # ── image ──
    async def generate_image(self, prompt: str, size: Optional[str] = None) -> MuseImage:
        self._require_key()
        if not (prompt or "").strip():
            raise ValueError("Nothing to draw — the prompt is empty.")
        self.check_prompt(prompt)
        model = self.image_model
        payload: Dict[str, Any] = {"model": model, "prompt": prompt, "n": 1}
        if size:
            payload["size"] = size
        resp = await self._post("/images/generations", payload)
        try:
            body = resp.json()
            item = body["data"][0]
        except Exception:
            raise ProviderError("unexpected image response", provider=self.name,
                                user_message="Muse sent back something we couldn't read.")
        provenance: Dict[str, Any] = {k: v for k, v in body.items() if k != "data"}
        provenance.update({k: v for k, v in item.items() if k not in ("b64_json", "url")})
        headers = {k.lower(): v for k, v in resp.headers.items()
                   if any(w in k.lower() for w in _PROVENANCE_HEADER_WORDS)}
        if headers:
            provenance["response_headers"] = headers
        mime = "image/png"
        if item.get("b64_json"):
            try:
                data = base64.b64decode(item["b64_json"], validate=True)
            except Exception:
                raise ProviderError("bad base64", provider=self.name,
                                    user_message="Muse sent back a damaged image.")
        elif item.get("url"):
            data, mime = await self._download(str(item["url"]))
        else:
            raise ProviderError("no image in response", provider=self.name,
                                user_message="Muse answered without an image.")
        if not data:
            raise ProviderError("empty image", provider=self.name, user_message="Muse sent back an empty image.")
        mime = str(item.get("mime_type") or item.get("content_type") or mime)
        return MuseImage(data=data, mime=mime, model=model, provenance=provenance)

    async def _download(self, url: str):
        """Fetch a returned image URL. No Authorization header — the key never leaves api.meta.ai."""
        if not url.startswith("https://"):
            raise ProviderError("non-https image url", provider=self.name,
                                user_message="Muse pointed at an image we won't pull over an unsecured link.")
        async with base.http_client(timeout=self.timeout_s) as client:
            try:
                resp = await client.get(url)
            except httpx.TransportError as exc:
                raise ProviderError(f"download failed: {type(exc).__name__}", provider=self.name,
                                    user_message="Muse made the image but we couldn't pull it down — check your dev.meta.ai usage before running again.")
        if resp.status_code != 200:
            raise ProviderError(f"download http {resp.status_code}", provider=self.name,
                                user_message="Muse made the image but we couldn't pull it down.")
        return resp.content, resp.headers.get("content-type", "image/png").split(";")[0].strip() or "image/png"

    async def generate(self, req: GenerationRequest, dest: Path) -> MediaAsset:
        if req.capability != "text_to_image":
            raise self._unsupported(req.capability)
        img = await self.generate_image(req.prompt)
        dest = Path(dest)
        base.atomic_write_bytes(dest, img.data)           # bytes exactly as received
        sidecar = dest.with_name(dest.name + ".provenance.json")
        base.atomic_write_bytes(sidecar, json.dumps(
            {"provider": self.name, "model": img.model, "ai_generated": True,
             "disclosure": img.disclosure, "provenance": img.provenance}, indent=2).encode("utf-8"))
        return MediaAsset(
            path=dest, mime=img.mime,
            usage={"provider": self.name, "unit": "images", "amount": 1},
            meta={"model": img.model, "ai_generated": True, "provenance": img.provenance,
                  "provenance_file": str(sidecar), "disclosure": img.disclosure},
        )
